django_documentation_part4/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),

]

django_documentation_part4/polls/urls.py
from django.urls import path

from polls.views import homepage, questions_list, question_detail, question_vote, question_add

app_name = 'polls'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('questions/', questions_list, name='questions_lists'),
    path('questions/<int:pk>/', question_detail, name='question_detail'),
    path('questions/<int:vote_id>/vote/', question_vote, name='question_vote'),
    path('questions/add/', question_add, name='question_add'),

]

django_documentation_part4/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', null=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.BooleanField)
    choise_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    is_true = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.question} - {self.choise_text} - {self.is_true}"

django_documentation_part4/polls/forms.py
from django import forms

from polls.models import Question


class QuestionForm(forms.ModelForm):
    # text = forms.CharField(label="Question text")
    # pub_date = forms.DateTimeField()

    class Meta:
        model = Question
        fields = ("question_text", "pub_date")

django_documentation_part4/polls/views.py
# from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse, Http404
# from .models import Question, Choice
# from django.shortcuts import get_object_or_404, render
#
#
# # Create your views here.
#
# def homepage(request):
#     return render(request, 'home.html')
#
#
# def questions_list(request):
#
#  # questions = Question.objects.all()
#  # response = ''
#  # for index ,question in enumerate(questions):
#  #     response += f"{index + 1 }. {question.question_text}<br>"
#  # return HttpResponse(f"Assalumu Akeykum <br>{response}")
#
#  questions = Question.objects.all()
#
#  context = {
#      'questions': questions
#  }
#  return render(request, 'polls/questions.html', context=context)
#
#
#
# def questions_detail(request, pk):
#     # try:
#     #     question = Question.objects.get(id=pk)
#     # except Question.DoesNotExist:
#     #     raise Http404
#     # else:
#     #     return HttpResponse(f"Question text: {question.question_text}<br>pub_date: {question.pub_date}")
#     question = get_object_or_404(Question, id=pk)
#
#     context = {
#         'question': question
#     }
#     return render(request, 'polls/question_detail.html', context= context)



from django.contrib.messages import SUCCESS, ERROR
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect


from polls.forms import QuestionForm
from polls.models import Question, Choice
from django.contrib import messages

def homepage(request):
    return render(request, 'home.html')


def questions_list(request):
    questions = Question.objects.all()

    context = {
        "questions": questions
    }

    return render(request, 'polls/questions.html', context=context)


def question_detail(request, pk):
    question = get_object_or_404(Question, id=pk)

    context = {
        "question": question,
    }

    return render(request, 'polls/question_detail.html', context=context)


def question_vote(request, vote_id):
    choice = request.POST.get('choice')
    print(choice)
    question = get_object_or_404(Question, id=vote_id)
    try:
        selected_choice = question.choice_set.get(pk=choice)
    except Choice.DoesNotExist:
        raise Http404("Choice doesn't exist.")
    else:
        selected_choice.votes += 1
        selected_choice.save()
        if selected_choice.is_true:
            messages.add_message(request, SUCCESS, 'Your choice is correct.')
            return HttpResponse('Your choice is correct.')
        else:
            messages.add_message(request, ERROR, 'Your choice is incorrect.')
            return HttpResponse('Your choice is incorrect.')
        # return redirect("polls:questions_list")


def question_add(request):
    form = QuestionForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("polls:questions_list")
    return render(request, 'polls/add_question.html', {"form": form})

django_documentation_part4/templates/base.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    {% block title %}#}
{#        <title>Homepage</title>#}
{#    {% endblock %}#}
{##}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"#}
{#          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">#}
{##}
{#</head>#}
{#<body>#}
{##}
{#<nav class="navbar navbar-expand-lg bg-primary-subtle">#}
{#    <div class="container-fluid">#}
{#        <a class="navbar-brand" href="{% url 'polls:homepage' %}">P10 Test Project</a>#}
{#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"#}
{#                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="{% url 'polls:homepage' %}">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'polls:questions_lists' %}">Link</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"#}
{#                       aria-expanded="false">#}
{#                        Dropdown#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled">Disabled</a>#}
{#                </li>#}
{#            </ul>#}
{#            <form class="d-flex" role="search">#}
{#                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#                <button class="btn btn-outline-success" type="submit">Search</button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#</nav> #}
{#v#}
{#<a href="{% url 'polls:homepage' %}"></a>#}
{##}
{#{% block content %}#}
{##}
{#{% endblock %}#}
{##}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Homepage</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-primary-subtle">
    <div class="container">
        <a class="navbar-brand" href="{% url 'polls:homepage' %}">P10 Test Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'polls:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <br>
                <br>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

</body>

</html>

django_documentation_part4/templates/home.html
{#<!doctype html>#}
{#<html lang="en" data-bs-theme="dark">#}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <title>Bootstrap demo</title>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">#}
{#  </head>#}
{#  <body>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>#}
{##}
{#    <nav class="navbar navbar-expand-lg bg-success-subtle">#}
{#    <div class="container-fluid">#}
{#        <a class="navbar-brand" href="#">P10 Test Project</a>#}
{#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"#}
{#                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="{% url 'polls:homepage' %}">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'polls:questions_lists' %}">Link</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"#}
{#                       aria-expanded="false">#}
{#                        Dropdown#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled">Disabled</a>#}
{#                </li>#}
{#            </ul>#}
{#            <form class="d-flex" role="search">#}
{#                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#                <button class="btn btn-outline-success" type="submit">Search</button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}
{##}
{#  <div class="container">#}
{#  <h1>Hello: My nama Aziz</h1>#}
{#  <p class="h1">SAlom do'stim nima gaplar</p>#}
{#  <h1>Assalomu aleykum <span style="color: beige">Yaxshimisz</span> </h1>#}
{#      <br>#}
{#      <a class="btn btn-primary" href="{% url 'polls:questions_lists'  %}" role="button">Click to question</a>#}
{#</div>#}
{##}
{#  <h1>Hello: My name Aziz</h1>#}
{#<h1>Salom do'stim nima <span style='color:#a2ff00'>gaplar</span></h1>#}
{#<h1>Assalomu aleykum <span style="color: aqua">Yaxshimisz</span></h1>#}
{#<br>#}
{#<a href="{% url 'polls:questions_lists' %}"> Click to questions</a>#}
{##}
{##}
{#  </body>#}
{#</html>#}



{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <p class="h1">You can find questions here!</p>
        <br>
{#        <a href="{% url 'polls:questions_lists' %}">Click to questions</a>#}
    <a href="{% url 'polls:questions_lists' %}" class="btn btn-primary" role="button" data-bs-toggle="button">Click to questions</a>


    </div>
{% endblock %}

django_documentation_part4/templates/polls/add_question.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{#    <div class="container">#}
{#        <form action="{% url 'polls:question_add' %}" method="post">#}
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            <button type="submit" class="btn btn-success">Add</button>#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}

{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form action="{% url 'polls:question_add' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>
{% endblock %}

django_documentation_part4/templates/polls/question_detail.html
{#<!doctype html>#}
{#<html lang="en" data-bs-theme="dark">#}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <title>Bootstrap demo</title>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">#}
{#  </head>#}
{#  <body>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>#}
{##}
{##}
{#<b>Text: </b>{{ question.question_text }}#}
{#<br>#}
{#<b>Publication date: </b>{{question.pub_date }}#}
{#<hr>#}
{##}
{#<a href="{% url 'polls:questions_lists' %}">⬅️ Orqaga</a>#}
{##}
{#<a class="btn btn-primary" href="{% url 'polls:questions_lists' %}" role="button">️️️️⬅️orqaga</a>#}
{#  <a class="btn btn-primary" href="{% url 'polls:homepage' %}" role="spinbutton">Home</a>#}
{#    <a class="btn btn-primary" href="{% url 'polls:questions_lists' %}" role="spinbutton">Orqaga</a>#}
{#</body>#}
{#</html>#}


{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form action="{% url 'polls:question_vote'  question.id %}" method="post">
            {% csrf_token %}
            <b>Text:</b> {{ question.question_text }}
            <br>
            <b>Publication date:</b> {{ question.pub_date }}
             {% for choice in question.choices.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" value="{{ choice.id}}"
                           id="{{ choice.id }}">
                    <label class="form-check-label" for="{{ choice.id }}">
                        {{ choice.text }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Submit</button>
            <br>
            <br>
            <a class="mt-5" href="{% url 'polls:questions_lists' %}">
                <button type="button" class="btn btn-outline-primary">Back to questions</button>
            </a>
        </form>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

django_documentation_part4/templates/polls/questions.html
{#<!doctype html>#}
{#<html lang="en" data-bs-theme="dark">#}
{##}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <title>Bootstrap demo</title>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">#}
{#  </head>#}
{#  <body>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>#}
{##}
{##}
{#<h2>Questions list page</h2>#}
{##}
{#<ul>#}
{#{% for question in questions%}#}
{#    <li><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_text }}</a></li>#}
{##}
{#{% endfor %}#}
{##}
{#</ul>#}
{##}
{#</body>#}
{#</html>#}


{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Questions list page</h2>

        <div class="list-group">
            {% for question in questions %}
                <a href="{% url 'polls:question_detail' question.id %}">
                    <button type="button" class="list-group-item list-group-item-action">{{ question.question_text}}</button>
                </a>
            {% endfor %}
        </div>


    </div>
{% endblock %}